Time to read keyword file = 0.054 seconds
Warning - SET_NODE 1 not found:
  Referenced in *BOUNDARY_PRESCRIBED_MOTION_SET ID = 1
Warning - SET_NODE 1 not found:
  Referenced in *BOUNDARY_SPC_SET ID = 1
Warning - SET_NODE 2 not found:
  Referenced in *BOUNDARY_SPC_SET ID = 2
Warning - DEFINE_CURVE 4 not found:
  Referenced in *MAT_DAMAGE_3 ID = 1
Warning - SET_NODE 1 not found:
  Referenced in *LOAD_NODE_SET ID = 1
Message 0
